function gallery(){
  $('#snake').click(function(ev) { 
    ev.preventDefault(); 
    bootbox.alert('<h4 class="text-center">Snake Game</h4><hr><img class="img-responsive img-center" src="img/snake_game.png"><br/><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/p5-snake-game" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/p5-snake-game/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  
  $('#angular-quiz').click(function(ev) { 
    ev.preventDefault();
    bootbox.alert('<h4 class="text-center">Angular Quiz</h4><hr><img class="img-responsive img-center" src="img/angular-quiz.png"><br/><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/angular-turtle-quiz/" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/angular-turtle-quiz/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#flappy').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Flappy Ball Game</h4><hr><img class="img-responsive img-center" src="img/flappy_ball.png"><br/><p class="text-center"></p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/p5-flappyball" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/p5-flappyball/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#infusion').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Infusion</h4><hr><img class="img-responsive img-center" src="img/infusion.jpg"><br/><p class="text-center"></p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/Infusion" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/Infusion/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#typing').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Typing test</h4><hr><img class="img-responsive img-center" src="img/typing.png"><br/><hr><p class="text-center"></p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/jquery-typingtest" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/jquery-typingtest/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#scatter').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Scatter Plot</h4><hr><img class="img-responsive img-center" src="img/scatter.png"><hr><p class="text-center"></p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/d3-fcd-scatterplot" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/d3-fcd-scatterplot/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#gdp').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">GDP</h4><hr><img class="img-responsive img-center" src="img/gdp.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/d3-freecodecamp-gdp" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/d3-freecodecamp-gdp" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#patent').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Mobile Patent Suits</h4><hr><img class="img-responsive img-center" src="img/patent.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/d3-forcelayout-mobilepatent" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/d3-forcelayout-mobilepatent" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#vesco').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Vesco</h4><hr><img class="img-responsive img-center" src="img/vesco.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/vesco" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/vesco" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#songs').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Dutch Top 2000 Songs</h4><hr><img class="img-responsive img-center" src="img/songs.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/dutchTop2000" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/dutchTop2000" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#meteor').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Meteorites Landing</h4><hr><img class="img-responsive img-center" src="img/meteor.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/d3-freecodecamp-mapping" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/d3-freecodecamp-mapping" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#heat_map').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Heat Map</h4><hr><img class="img-responsive img-center" src="img/heat_map.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/d3-freecodecamp-heatmap" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/d3-freecodecamp-heatmap" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#alumni-connect').click(function(ev) { 
    ev.preventDefault(); 
    bootbox.alert('<h4 class="text-center">Alumni Connect</h4><hr><img class="img-responsive img-center" src="img/alumni-connect.png"><hr><p class="text-center">A social networking platform that connects Alumni with the students.</p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/alumni-connect" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://165.227.199.11/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });

    $('#dnd-blocks').click(function(ev) { 
      ev.preventDefault(); 
      bootbox.alert('<h4 class="text-center">Drag and Drop Builder</h4><hr><img class="img-responsive img-center" src="img/dnd-blocks.png"><hr><p class="text-center">A Drag and Drop Builder built with Vanilla JavaScript</p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/drag-and-drop" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://dnd-blocks.surge.sh/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
    $('#you-search').click(function(ev) { 
      ev.preventDefault(); 
      bootbox.alert('<h4 class="text-center">YouSearch</h4><hr><img class="img-responsive img-center" src="img/you-search.png"><hr><p class="text-center">A Drag and Drop Builder built with Vanilla JavaScript</p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/YouSearch" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://varunreddy5.github.io/YouSearch" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  
}

$(document).ready(gallery);
