function gallery(){
  $('#snake').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Snake Game</h4><hr><img class="img-responsive img-center" src="img/snake_game.png"><br/><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/p5-snake-game" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/p5-snake-game/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#angular-quiz').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Angular Quiz</h4><hr><img class="img-responsive img-center" src="img/angular-quiz.png"><br/><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/angular-turtle-quiz/" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/angular-turtle-quiz/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#flappy').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Flappy Ball Game</h4><hr><img class="img-responsive img-center" src="img/flappy_ball.png"><br/><p class="text-center"></p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/p5-flappyball" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/p5-flappyball/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#infusion').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Infusion</h4><hr><img class="img-responsive img-center" src="img/infusion.jpg"><br/><p class="text-center"></p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/Infusion" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/Infusion/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#typing').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Typing test</h4><hr><img class="img-responsive img-center" src="img/typing.png"><br/><hr><p class="text-center"></p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/jquery-typingtest" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/jquery-typingtest/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#scatter').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Scatter Plot</h4><hr><img class="img-responsive img-center" src="img/scatter.png"><hr><p class="text-center"></p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/d3-fcd-scatterplot" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/d3-fcd-scatterplot/" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#gdp').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">GDP</h4><hr><img class="img-responsive img-center" src="img/gdp.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/d3-freecodecamp-gdp" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/d3-freecodecamp-gdp" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#patent').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Mobile Patent Suits</h4><hr><img class="img-responsive img-center" src="img/patent.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/d3-forcelayout-mobilepatent" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/d3-forcelayout-mobilepatent" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#vesco').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Vesco</h4><hr><img class="img-responsive img-center" src="img/vesco.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/vesco" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/vesco" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
   $('#songs').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Dutch Top 2000 Songs</h4><hr><img class="img-responsive img-center" src="img/songs.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/dutchTop2000" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/dutchTop2000" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#meteor').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Meteorites Landing</h4><hr><img class="img-responsive img-center" src="img/meteor.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/d3-freecodecamp-mapping" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/d3-freecodecamp-mapping" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#heat_map').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Heat Map</h4><hr><img class="img-responsive img-center" src="img/heat_map.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/d3-freecodecamp-heatmap" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://varunreddy5.github.io/d3-freecodecamp-heatmap" target="_blank"><button type="button" class="btn btn-danger">Launch Demo</button></a></div>'); });
  $('#job-board').click(function(ev) { ev.preventDefault(); bootbox.alert('<h4 class="text-center">Job Board</h4><hr><img class="img-responsive img-center" src="img/job_board.png"><hr><p class="text-center"> </p><div class="col-md-offset-3 col-md-9"><a href="https://github.com/varunreddy5/job-board" target="_blank"><button type="button" class="btn btn-success">Github URL</button></a>&nbsp;&nbsp;&nbsp;&nbsp;</div>'); });
}

$(document).ready(gallery);
